import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

import LinkServer from "./components/disc-link";
import DiscLink from "./components/disc-link";
import IconDiscord from "./components/icons/icon-discord";

const whitney = localFont({
  src: [
    {
      path: "./fonts/whitney/whitney-light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/whitney/whitney-book.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/whitney/whitney-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/whitney/whitney-semiBold.woff",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-whitney",
});

const ginto = localFont({
  src: [
    {
      path: "./fonts/ginto/ginto-semibold.woff",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-ginto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const homeIcon = <IconDiscord className="h-[30px] w-[30px]" />;
  return (
    <html lang="en">
      <body
        className={`${whitney.variable} ${ginto.variable} font-whitney antialiased`}
      >
        <div className="flex h-screen text-gray-300">
          <div className="hide-scrollbar space-y-2 overflow-y-scroll bg-zinc-900 p-3">
            <DiscLink href={"/"} icon={homeIcon} />
            <DiscLink href={"/servers/1"} icon={"S1"} />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
