import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import NavLink from "./components/nav-link";
import IconDiscord from "./components/icons/icon-discord";
import Image from "next/image";

const whitney = localFont({
  src: [
    {
      path: "./fonts/whitney/whitney-light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/whitney/whitney-book.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/whitney/whitney-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/whitney/whitney-semiBold.woff",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-whitney",
});

const ginto = localFont({
  src: [
    {
      path: "./fonts/ginto/ginto-semibold.woff",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-ginto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const servers = [
  { id: "1", src: "/images/mirage.png" },
  { id: "2", src: "/images/tailwind.png" },
  { id: "3", src: "/images/next.png" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const homeIcon = <IconDiscord className="h-[30px] w-[30px]" />;
  return (
    <html lang="en">
      <body
        className={`${whitney.variable} ${ginto.variable} font-whitney antialiased`}
      >
        <div className="flex h-screen text-gray-300">
          <div className="hide-scrollbar space-y-2 overflow-y-scroll bg-zinc-900 p-3">
            <NavLink href={"/"}>{homeIcon}</NavLink>
            <hr className="mx-2 rounded border-t-2 border-t-white/[.06]" />
            {servers.map(({ id, src }) => {
              return (
                <NavLink key={id} href={`/servers/${id}`}>
                  <Image width="48" height="48" src={src} alt={""} />
                </NavLink>
              );
            })}
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
